eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:10087/eureka/
server: 
  port: 19018 
spring: 
  application: 
    name: eurekaclient
spring: 
  zipkin: 
    base-url: http://localhost:9411 
  sleuth: 
    sampler: 
      percentage: 1.0    
